name: Build Makefile for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Android NDK
      run: |
        mkdir -p $HOME/android-sdk/ndk
        cd $HOME/android-sdk/ndk
        curl -L https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip -o ndk.zip
        unzip -q ndk.zip
        export ANDROID_NDK_HOME=$HOME/android-sdk/ndk/android-ndk-r21e

    - name: Build Makefile for ARMv7
      run: make CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang++ AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar ARCH=armv7

    - name: Build Makefile for ARMv8A
      run: make CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar ARCH=armv8a
